### ISSUE TITLE
v8 inspect command returns error

### ISSUE THREAD

**Issue by trevnorris** [indutny/llnode#29]
Using lldb 3.8 on Ubuntu 16.04 (4.4.0-34 kernel) with latest llnode. Running on node v6.6.0 Release build.

Getting `error: Failed to evaluate expression` when attempting to `inspect` a function address. Here's an abbreviated log:
```
node_v6 ((v6.6.0)) $ lldb-3.8 -- ./node -e 'Buffer(1024).indexOf(Buffer(3))'
(lldb) target create "./node"
Current executable set to './node' (x86_64).
(lldb) settings set -- target.run-args  "-e" "Buffer(1024).indexOf(Buffer(3))"
(lldb) b 'node::Buffer::IndexOfBuffer(v8::FunctionCallbackInfo<v8::Value> const&)'
Breakpoint 1: where = node`node::Buffer::IndexOfBuffer(v8::FunctionCallbackInfo<v8::Value> const&), address = 0x0000000000f53b40

(lldb) v8 bt 7
 * thread #1: tid = 2513, 0x0000000000f53b40 node`node::Buffer::IndexOfBuffer(v8::FunctionCallbackInfo<v8::Value> const&), name = 'node', stop reason = breakpoint 1.1
    frame #0: 0x0000000000f53b40 node`node::Buffer::IndexOfBuffer(v8::FunctionCallbackInfo<v8::Value> const&)
    frame #1: 0x000000000090107c node`v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) + 348
    frame #2: 0x000000000093530c node`v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>) + 1052
    frame #3: 0x000000000093f4e8 node`v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) + 456
    frame #4: 0x00000ccd50e092a7 <exit>
    frame #5: 0x00000ccd50f3fa52 bidirectionalIndexOf(this=0x00001b416de04381:<undefined>, 0x00003628897e5029:<ArrayBufferView 0x0000000001baad40+0:1024>, 0x00003628897e52c1:<ArrayBufferView 0x0000000001baad40+1024:3>, <Smi: 0>, 0x00001b416de04381:<undefined>, 0x00001b416de043c1:<true>) at buffer.js:559:30 fn=0x000036288973e9a9
  * frame #6: 0x00000ccd50f3f401 indexOf(this=0x00003628897e5029:<ArrayBufferView 0x0000000001baad40+0:1024>, 0x00003628897e52c1:<ArrayBufferView 0x0000000001baad40+1024:3>, 0x00001b416de04381:<undefined>, 0x00001b416de04381:<undefined>) at buffer.js:622:44 fn=0x00002272434079c1
(lldb) v8 print 0x00002272434079c1
0x00002272434079c1:<function: indexOf at buffer.js:622:44>
(lldb) v8 inspect 0x00003628897e5029
0x00003628897e5029:<ArrayBufferView 0x0000000001baad40+0:1024>
(lldb) v8 inspect 0x00002272434079c1
error: Failed to evaluate expression
```

At the end I also show that `print` works on a fn address, and `inspect` works on an object.

**Comment by indutny** [comment]
@trevnorris could you please give a try to https://github.com/indutny/llnode/pull/30 ? It appears to be fixing the problem locally.

**Comment by trevnorris** [comment]
@indutny Confirmed that the patch fixes the issue. Thanks for fixing that so quickly!
